### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'search'

### ISSUE THREAD

**Issue by sferket** [vaab/report_birt#1]
This module seems to be helpful for us, thanks for sharing it. Problem is we cannot get it working.
After installing the module on 6.0.3 we keep getting errors. These errors appear in places where we would not expect them.
For example Administration -> Modules -> Modules generates this error:

Traceback (most recent call last):
  File "/home/ferkets/openerp/openerp-server-6.0.4/bin/netsvc.py", line 489, in dispatch
    result = ExportService.getService(service_name).dispatch(method, auth, params)
  File "/home/ferkets/openerp/openerp-server-6.0.4/bin/service/web_services.py", line 599, in dispatch
    res = fn(db, uid, _params)
  File "/home/ferkets/openerp/openerp-server-6.0.4/bin/osv/osv.py", line 122, in wrapper
    return f(self, dbname, *args, *_kwargs)
  File "/home/ferkets/openerp/openerp-server-6.0.4/bin/osv/osv.py", line 176, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/home/ferkets/openerp/openerp-server-6.0.4/bin/osv/osv.py", line 167, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/home/ferkets/openerp/openerp-server-6.0.4/bin/osv/orm.py", line 1671, in fields_view_get
    context)
  File "/home/ferkets/openerp/openerp-server-6.0.3/bin/addons/base_calendar/base_calendar.py", line 1816, in get
    meta, context, res_id_req, without_user, key2_req)
  File "/home/ferkets/openerp/openerp-server-6.0.3/bin/addons/base/ir/ir_values.py", line 213, in get
    res = filter(None, map(lambda x: _result_get(x, keys), result))
  File "/home/ferkets/openerp/openerp-server-6.0.3/bin/addons/base/ir/ir_values.py", line 213, in <lambda>
    res = filter(None, map(lambda x: _result_get(x, keys), result))
  File "/home/ferkets/openerp/openerp-server-6.0.3/bin/addons/base/ir/ir_values.py", line 201, in _result_get
    datas = self.pool.get(model).read(cr, uid, [int(id)], fields, context)
  File "/home/ferkets/openerp/openerp-server-6.0.4/bin/osv/orm.py", line 2947, in read
    result = self._read_flat(cr, user, select, fields, context, load)
  File "/home/ferkets/openerp/openerp-server-6.0.4/bin/osv/orm.py", line 3067, in _read_flat
    res2 = self._columns[f].get(cr, self, ids, f, user, context=context, values=res)
  File "/home/ferkets/openerp/openerp-server-6.0.4/bin/osv/fields.py", line 494, in get
    ids2 = obj.pool.get(self._obj).search(cr, user, self._domain + [(self._fields_id, 'in', ids)], limit=self._limit, context=context)
AttributeError: 'NoneType' object has no attribute 'search'

**Comment by vaab** [comment]
This might not be related to `report_birt`. You'll need to dig a little bit to uncover wether it is related to `report_birt`. 

Anyway, digging will help you going forward. Let me help you:

This error is because `obj.pool.get(self._obj)` is returning `None`... line `494` in `/home/ferkets/openerp/openerp-server-6.0.4/bin/osv/fields.py`. I would suggest you to put a `print` statement (or a logging instruction) or a `try/except` control structure with any previous suggestion, or even a `import pdb; pdb.set_trace()`... Your objective is to print out the value of `self._obj`.

As this error is quite common, you could think about a solution you could leave in the code harmlessly.

This error happens when your database is not in sync to the Python code (the modules) the server has access. In other words, the database (in postgres) has a list of the installed module, and each modules brings models which have their definition stored also in database. When OpenERP needs to effectively bring `alive` an object, it'll need to dress it with Python code. 

If these instructions are not clear enough for you, I would be happy to give you the exact code to type in.

Thank you for your interest in `report_birt`. 

In case you need more information:

The instruction `obj.pool.get(module_name)` is asking for the python class corresponding to the model named `module_name`. All python class are registered in a big registery (which is often referred with the "pool" variable) at loading time thanks to the parsing of the `__init__.py` of your modules which in turn will load all the `*.py` and all the python files that are imported recursively from your `__init__.py`. All the python classes inheriting from "osv.osv" AND that are instanciated once will then be registered in the `pool` with their `_name` attribute as key.

**Comment by sferket** [comment]
Ok, I tried it again. 
I installed a clean database on a new server. 
In the new database I can open Modules, it'll display the modules. 
After installing report_birt, I cannot open the modules listing anymore. 
It'll give me:

Traceback (most recent call last):
  File "/opt/openerp/openerp-server-6.0.3/bin/netsvc.py", line 489, in dispatch
    result = ExportService.getService(service_name).dispatch(method, auth, params)
  File "/opt/openerp/openerp-server-6.0.3/bin/service/web_services.py", line 599, in dispatch
    res = fn(db, uid, _params)
  File "/opt/openerp/openerp-server-6.0.3/bin/osv/osv.py", line 122, in wrapper
    return f(self, dbname, *args, *_kwargs)
  File "/opt/openerp/openerp-server-6.0.3/bin/osv/osv.py", line 176, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp/openerp-server-6.0.3/bin/osv/osv.py", line 167, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp/openerp-server-6.0.3/bin/osv/orm.py", line 1669, in fields_view_get
    context)
  File "/opt/d00003/openerp/server/bin/addons/base/ir/ir_values.py", line 213, in get
    res = filter(None, map(lambda x: _result_get(x, keys), result))
  File "/opt/d00003/openerp/server/bin/addons/base/ir/ir_values.py", line 213, in <lambda>
    res = filter(None, map(lambda x: _result_get(x, keys), result))
  File "/opt/d00003/openerp/server/bin/addons/base/ir/ir_values.py", line 201, in _result_get
    datas = self.pool.get(model).read(cr, uid, [int(id)], fields, context)
  File "/opt/openerp/openerp-server-6.0.3/bin/osv/orm.py", line 2944, in read
    result = self._read_flat(cr, user, select, fields, context, load)
  File "/opt/openerp/openerp-server-6.0.3/bin/osv/orm.py", line 3064, in _read_flat
    res2 = self._columns[f].get(cr, self, ids, f, user, context=context, values=res)
  File "/opt/openerp/openerp-server-6.0.3/bin/osv/fields.py", line 481, in get
    ids2 = obj.pool.get(self._obj).search(cr, user, self._domain + [(self._fields_id, 'in', ids)], limit=self._limit, context=context)
AttributeError: 'NoneType' object has no attribute 'search'

**Comment by vaab** [comment]
Thank you for reporting this. This is the same error, could you check that your report_birt addon directory is correctly named "report_birt" and not something else ? If yes, could you describe me with more details how did you install report_birt ? (there are numerous way to do this.)

**Comment by sferket** [comment]
Valentin,

We install the addons in a seporate directory that we refer to using the
addons_path in the configuration file.
These are the steps we did to install it:
- Create new directory under addons called report_birt
- cd to that directory
- git clone https://github.com/vaab/report_birt.git
- ./autogen.sh
- Startup OpenERP web ad install the module from there

We run OpenERP 6.0.3 on an Ubuntu 10.04 64 bits server.

This is the contents of the directory report_birt:
*-rwxr-xr-x 1 root root 3847 2012-12-03 20:40 autogen.sh
-rw-r--r-- 1 root root  357 2012-12-03 20:40 birt.py
-rw-r--r-- 1 root root  670 2012-12-03 20:40 birt_report_parameter.py
-rw-r--r-- 1 root root 1002 2012-12-03 20:40 birt_report_parameter.xml
-rw-r--r-- 1 root root 4731 2012-12-03 20:40 birt_report.py
drwxr-xr-x 2 root root 4096 2012-12-03 20:40 doc
drwxr-xr-x 2 root root 4096 2012-12-03 20:40 i18n
-rw-r--r-- 1 root root   91 2012-12-03 20:40 **init**.py
-rw-r--r-- 1 root root 3842 2012-12-03 20:40 ir_report.py
-rw-r--r-- 1 root root 1004 2012-12-03 20:40 ir_report_view.xml
-rw-r--r-- 1 root root  608 2012-12-03 20:40 **openerp**.py
-rw-r--r-- 1 root root 2012 2012-12-03 20:40 README.rst
drwxr-xr-x 2 root root 4096 2012-12-03 20:40 security
*
Hope this helps you.

Thanks,
Stefaan

On Wed, Dec 5, 2012 at 9:59 AM, Valentin Lab notifications@github.comwrote:

> Thank you for reporting this. This is the same error, could you check that
> your report_birt addon directory is correctly named "report_birt" and not
> something else ? If yes, could you describe me with more details how did
> you install report_birt ? (there are numerous way to do this.)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/vaab/report_birt/issues/1#issuecomment-11033986.

## 

Met vriendelijke groet,
_Stefaan Ferket_

 *open2bizz *software en consultancy
de oprechte eenvoud

 Tel:   +31(0)8 500 20 265

 s.ferket@open2bizz.nl

www.open2bizz.nl

 *Eerlijke, betaalbare en  doeltreffende software oplossingen voor bedrijven
*

**Comment by vaab** [comment]
I checked on `6.0.3` and I managed to reproduce the bug you've reported. And I fixed it. Thank you for the bug report !. Could you please check that it's working for you and report it to me here ? Fix is already committed on master branch.

Please note that it seems that the simplest is to start back with a new openerp base (where previous version of `report_birt` were not installed) to make this check.

**Comment by sferket** [comment]
Thanks for the prompt response.

The fix does not fix the problem. These are the steps I did:

```
$ cd report_birt
$ git pull
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 6 (delta 4), reused 6 (delta 4)
Unpacking objects: 100% (6/6), done.
From https://github.com/vaab/report_birt
   b4b7c67..cabd0d4  master     -> origin/master
 * [new tag]         0.2        -> 0.2
Updating b4b7c67..cabd0d4
Fast-forward
 birt.py                  |    2 +-
 birt_report_parameter.py |    3 +++
 2 files changed, 4 insertions(+), 1 deletions(-)

$ ./autogen.sh
No changelog generated (gitchangelog not found)
Version updated to 0.2.
$
```

After this I dropped the original Database and created a new one, updated
the modules, re-installed report_birt.
Still the same problem:

```
AttributeError: 'NoneType' object has no attribute 'search'
```

**Comment by vaab** [comment]
did you stop and restart the openerp server ? This is needed so that the python code can be reloaded. (If this isn't enough, you could also try to delete `*.pyc` if there are any in `report_birt` directory).

I did a complete test with my patch and it works fine on my 6.0.3, and the `git pull` output you've reported seems good. The correction is in cabd0d4 and your branch is up to date now.

**Comment by sferket** [comment]
You're right. Forgot to restart. It's working fine now.
We'll continue with our evaluation.

Thanks, looks like a useful module for us.

On Wed, Dec 5, 2012 at 7:38 PM, Valentin Lab notifications@github.comwrote:

> o that the python code can b

## 

Met vriendelijke groet,
_Stefaan Ferket_

 *open2bizz *software en consultancy
de oprechte eenvoud

 Tel:   +31(0)8 500 20 265

 s.ferket@open2bizz.nl

www.open2bizz.nl

 *Eerlijke, betaalbare en  doeltreffende software oplossingen voor bedrijven
*
